"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Livro_1 = require("./Livro");
var Revista_1 = require("./Revista");
var Usuario_1 = require("./Usuario");
var Biblioteca_1 = require("./Biblioteca");
var livro1 = new Livro_1.Livro("O Senhor dos Anéis", 1954, "J.R.R. Tolkien", 1216);
var revista1 = new Revista_1.Revista("National Geographic", 2024, "NG Media", 150);
var usuario1 = new Usuario_1.Usuario("Maria Silva", 1);
var biblioteca = new Biblioteca_1.Biblioteca();
biblioteca.adicionarItem(livro1);
biblioteca.adicionarItem(revista1);
biblioteca.registrarUsuario(usuario1);
usuario1.emprestarItem(livro1);
biblioteca.emprestarItem(usuario1, revista1);
